services:
  web:
    working_dir: /app
    image: python
    port:
      - "5000:5000"
    depends_on:
      - db
    volumns:
      - ./app:/app
    command: ["sh", "script.sh"]

  db:
    working_dir: /db
    image: mysql
    port:
      - "3307:3306"
    volumns:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
